services:
  - type: web
    name: vglog2
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: TURSO_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
